### ISSUE TITLE
Incorrect definition of VarPtrArray for X64

### ISSUE THREAD

**Issue by WaynePhillipsEA** [fafalone/Lems64#5]
`Private Declare PtrSafe Function VarPtrArray Lib "msvbvm60" Alias "VarPtr" (Ptr() As Any) As Long`

Should be:

`Private Declare PtrSafe Function VarPtrArray Lib "msvbvm60" Alias "VarPtr" (Ptr() As Any) As LongPtr`

This is crashing in recent tB BETAs in the IDE due to changes in how the compiler allocates some of its memory, leading to other memory allocations now often utilizing the upper half of the memory addresses, which is helpful here in identifying this bug.

**Comment by fafalone** [comment]
Thanks for letting me know, issued a quick fix just for that on the current repo.
